### ISSUE TITLE
Guru meditation after closing the game

### ISSUE THREAD

**Issue by mlorenzati** [jotd666/jst#2]
Testing JST on an A500 with 2Megs, after I run the game successfully, when exiting with F10 the workbench crashes with a guru meditation.

**Comment by jotd666** [comment]
that is because there is not enough memory to quit properly. jst should
reset the amiga instead.

Le dim. 4 avr. 2021 à 07:42, Marcelo Lorenzati ***@***.***> a
écrit :

**Comment by mlorenzati** [comment]
I see, thanks! What's weird is that is happening even with the smallest games.
JFYI I'm running the game from an SD card in parallel port (if there is any issue between jst and external ports).
I'll try running the game without the WB loaded.
Is there a way to quit with a bash command the WB?

**Comment by jotd666** [comment]
found & fixed this issue in development version :)

**Comment by mlorenzati** [comment]
Nice! I'll try it asap thanks!

**Comment by bkodenkt** [comment]
Should this be fixed in the 7.1 version? Right now I make small batch scripts in Workbench 1.3, manually add a project icon with IconX as default tool and then start and quit games perfectly fine without guru.

I really like jst, nice work! Is it allowed to contribute directly to the "known good whdload packs" text file? Do you want feedback/issues regarding Workbench 1.3 and save/load problems?

**Comment by jotd666** [comment]
I have to setup a worrbench 1.3 environment. ATM I only has a cli
environment. Then yes I should fix such nasty bugs.

As I mentionned somewhere "known good whdload packs" would create too much
data. I'm more interested in "not working games" and you can contribute
directly here

https://docs.google.com/spreadsheets/d/1jHk_phH550-iy746wHPbDQxU0Ad6gZKu66Xk7oSQOt0/edit#gid=0
